### ISSUE TITLE
Not Functioning in Pycharm (IDE)

### ISSUE THREAD

**Issue by Christopher-Py** [mathstar13/clear#1]
Hi, so instead of the screen clearing, it just gives a little square character, almost like those object characters. I am using Pycharm Community Edition on Windows. Can someone please help me.

![Untitled4](https://user-images.githubusercontent.com/81348663/176885267-5cdacd77-8693-4a3b-b2f5-c8bbb05ad17d.png)
.

**Comment by andestef** [comment]
@Christopher-Py Your problem is that PyCharm doesn't automatically emulate the terminal in the output console, so it can not clear. From your PyCharm project, press `Alt+Shift+F10`. Then, click `Edit Configurations`. Scroll to emulations, and check the box `Emulate terminal in output console`. Finally, press `Apply`.
